<?php
$doctor = $this->doctor;
if ( $doctor instanceof Application_Model_Medical_Doctor ) : ?>
    <div class="doctor-box-item">
        <div class="doctor-box-item-img"><?
            ?><img src="<?=$doctor->getPhoto()->getPath(140, 140)?>" alt=""/>
        </div>
        <div class="doctor-box-item-info">
            <div class="doctor-box-item-name"><?=$doctor->getName()?></div>
            <div class="doctor-box-item-text"><?=$doctor->getDescription()?></div>
        </div>
        <div class="clear"></div>
    </div><?
endif;