<div class="clinic">
    <div class="fix">
        <div class="clinic-left-box">
            <div class="main-title">Клиника</div>
            <div class="clinic-text-box">
                В нашей клинике 183 м2 это как две трёхкомнатных квартиры в спальном районе.
                У каждого врача свой кабинет. Открылись мы в 2011 году, поэтому оборудование новое
                и современное (Chirana-dental, Kodak-trophy, NSK, VDW, Ems, W&H, Mocom, Euronda).
            </div>
            <div class="clinic-quote">
                <div class="clinic-quote-text">
                    <i class="ico quote-top-s-ico"></i>
                    <div class="simple-text">
                        <p>
                            Мы так хотели запустит сайт к новому году, что забыли о выходных.
                        </p>
                    </div>
                    <i class="ico quote-bottom-s-ico"></i>
                </div>
                <div class="quote-text-sign">— Илья Сергеевич</div>
            </div>
        </div>
        <div class="clinic-right-box">
            <div class="main-title">Вакансии</div>
            <div class="clinic-text-box">
                Врач терапевт. <br/> Напишите нам <a href="#">job@optima.ru</a>
            </div>
        </div>
        <div class="clear"></div>
        <?=$this->partial('blocks/index/parts/banner.phtml')?>
        <div class="doctor-box">
            <div class="doctor-box-item">
                <div class="doctor-box-item-img">
                    <img src="/s/public/images/big-doctor-1.png" alt=""/>
                </div>
                <div class="doctor-box-item-info">
                    <div class="doctor-box-item-name">
                        Павел Дьяченко
                    </div>
                    <div class="doctor-box-item-text">
                        Павел наш ортодонт. Он отвечает за красивую улыбку.
                        Закончил Саратовский Мед и проходил курс об имлантации
                        в Израиле.
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="doctor-box-item">
                <div class="doctor-box-item-img">
                    <img src="/s/public/images/big-doctor-1.png" alt=""/>
                </div>
                <div class="doctor-box-item-info">
                    <div class="doctor-box-item-name">
                        Павел Дьяченко
                    </div>
                    <div class="doctor-box-item-text">
                        Павел наш ортодонт. Он отвечает за красивую улыбку.
                        Закончил Саратовский Мед и проходил курс об имлантации
                        в Израиле.
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="doctor-box-item">
                <div class="doctor-box-item-img">
                    <img src="/s/public/images/big-doctor-1.png" alt=""/>
                </div>
                <div class="doctor-box-item-info">
                    <div class="doctor-box-item-name">
                        Павел Дьяченко
                    </div>
                    <div class="doctor-box-item-text">
                        Павел наш ортодонт. Он отвечает за красивую улыбку.
                        Закончил Саратовский Мед и проходил курс об имлантации
                        в Израиле.
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clinic-comments">
            <div class="fix">
                <div class="main-title">Отзывы</div>
                <div class="comments-item-list">
                    <div class="comments-item">
                        <div class="comments-item-author">
                            <div class="comments-item-author-name">Коляновна</div>
                            <div class="comments-item-author-post">28 января 2014</div>
                        </div>
                        <div class="comments-item-text">
                            <div class="simple-text">
                                <p>Достаточно чистить зубы два-три раза в день и использовать для чистки зубную нить. Ополаскиватель для рта также иммеет хорошие рекомендации.</p>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="comment-btn-box">
                    <a class="button comments-btn" href="#">Напиcать отзыв...</a>
                    <div class="popup-box up-show">
                        <i class="ico popup-tile"></i>
                        <div class="popup-client-box">
                            <div class="popup-client-box-item">
                                <input type="text" placeholder="Имя"/>
                            </div>
                            <div class="popup-client-box-item">
                                <input type="text" placeholder="Телефон"/>
                            </div>
                            <textarea></textarea>
                            <div class="popup-client-box-item">
                                <input class="button popup-send-btn" type="button" value="Записатся"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-thx">Благодарим вас. <br/> Отзыв будет опубликован через 1—2 дня.</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>