<div class="comments">
    <div class="fix">
        <div class="main-title">Советы</div>
        <div class="tips-btn-box">
            <a class="button comments-btn" href="#">Спросить совета</a>
            <div class="popup-box">
                <i class="ico popup-tile"></i>
                <div class="popup-client-box">
                    <div class="popup-client-box-item">
                        <input type="text" placeholder="Имя"/>
                    </div>
                    <div class="popup-client-box-item">
                        <input type="text" placeholder="Телефон"/>
                    </div>
                    <textarea></textarea>
                    <div class="popup-client-box-item">
                        <input class="button popup-send-btn" type="button" value="Записатся"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="popup-thx">Спасибо за участие. Предлагаем ознакомиться с уже опубликованными ниже ответами.</div>
        <div class="clear"></div>
        <div class="comments-item">
            <div class="comments-item-name">Как бороться с зубным камнем?</div>
            <div class="comments-item-author">
                <div class="comments-item-author-name">Илья Медведков</div>
                <div class="comments-item-author-post">главный врач</div>
            </div>
            <div class="comments-item-text">
                <div class="simple-text">
                    <p>Достаточно чистить зубы два-три раза в день и использовать для чистки зубную нить. Ополаскиватель для рта также иммеет хорошие рекомендации.</p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="comments-item">
            <div class="comments-item-name">Что такое зубной камень?</div>
            <div class="comments-item-author">
                <div class="comments-item-author-name">Илья Медведков</div>
                <div class="comments-item-author-post">главный врач</div>
            </div>
            <div class="comments-item-text">
                <div class="simple-text">
                    <p>Зубной камень — это известковое образование, возникающее на поверхности зуба, нередко распространяющееся на корень. Содержит большое количество микробов
                        и часто приводит к кариесу и повреждению десен. Зубной камень может различаться по твердости и по цвету: желтый мягкий и темный твердый. </p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="comments-item">
            <div class="comments-item-name">Технология уборки кабинетов клиники. Трудности и подводные камни. </div>
            <div class="comments-item-author">
                <div class="comments-item-author-name">Илья Медведков</div>
                <div class="comments-item-author-post">главный врач</div>
            </div>
            <div class="comments-item-text">
                <div class="simple-text">
                    <p>Чтобы убирать помещения в клинике, клининговые компании проводят курсы. На курсах рассказывают на что обращать внимание: использованные ватные тампоны, остатки зубов на полу, кровь в умывальнике. Эти вещи пугают пациентов, которые приходят следующими. </p>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>