<div class="comments">
    <div class="fix">
        <div class="main-title">Советы</div>
        <div class="tips-btn-box">
            <span class="form-activate-button button comments-btn">Спросить совета...</span>
            <div class="form-container popup-box" style="display: none">
                <i class="ico popup-tile"></i>
                <form action="">
                    <div class="popup-client-box">
                        <div class="popup-client-box-item">
                            <input name="visitor-name" data-alias="visitor_name" type="text" placeholder="Имя"/>
                        </div>
                        <div class="popup-client-box-item">
                            <input name="visitor-email" data-alias="visitor_email" type="text" placeholder="Электронная почта"/>
                        </div>
                        <div>
                            <textarea name="visitor-question" data-alias="visitor_question"></textarea>
                        </div>
                        <div class="popup-client-box-item">
                            <input class="form-submit-button button popup-send-btn" type="button" value="Спросить"/>
                        </div>
                    </div>
                </form>
                <div class="error-box popup-client-box" style="display: none">
                    <span class="error-message"></span>
                    <span class="form-try-again-button">Попробовать еще раз</span>
                </div>
            </div>
        </div>
        <div class="thank-you-box popup-thx" style="display: none">Спасибо за участие. Предлагаем ознакомиться с уже опубликованными ниже ответами.</div>
        <div class="clear"></div><?
        foreach ($this->advices as $advice) :
            echo $this->partial('blocks/advices/advice.phtml', array(
                'advice' => $advice
            ));
        endforeach
    ?></div>
</div><?
echo $this->headScript()->captureStart();
?>$(function() {
    Med.SimplePopupForm.init('<?=$this->url([], 'ask-question-ajax')?>', {
        "name": 'input[name="visitor-name"]',
        "email": 'input[name="visitor-email"]',
        "text": 'textarea[name="visitor-question"]'
    });
});<?
echo $this->headScript()->captureEnd();