<div class="comments">
    <div class="fix">
        <div class="main-title">Советы</div>
        <div class="tips-btn-box">
            <a class="button comments-btn" href="#">Спросить совета</a>
            <div class="popup-box" style="display: none">
                <i class="ico popup-tile"></i>
                <div class="popup-client-box">
                    <div class="popup-client-box-item">
                        <input type="text" placeholder="Имя"/>
                    </div>
                    <div class="popup-client-box-item">
                        <input type="text" placeholder="Телефон"/>
                    </div>
                    <textarea></textarea>
                    <div class="popup-client-box-item">
                        <input class="button popup-send-btn" type="button" value="Записатся"/>
                    </div>
                </div>
            </div>
        </div>
        <div class="popup-thx">Спасибо за участие. Предлагаем ознакомиться с уже опубликованными ниже ответами.</div>
        <div class="clear"></div><?
        foreach ($this->advices as $advice) :
            echo $this->partial('blocks/advices/advice.phtml', array(
                'advice' => $advice
            ));
        endforeach
    ?></div>
</div>