<?php
$advice = $this->advice;
$doctor = $advice->getDoctor();
if ($advice instanceof Application_Model_Medical_Advice) : ?>
    <div class="comments-item">
        <div class="comments-item-name"><?=$advice->getVisitorQuestion()?></div>
        <div class="comments-item-author">
            <div class="comments-item-author-name"><?=$doctor ? $doctor->getName() : ''?></div>
            <div class="comments-item-author-post"><?
                echo $doctor ? $this->DoctorFormatter($doctor)->getFormattedPosts() : ''?></div>
        </div>
        <div class="comments-item-text">
            <div class="simple-text">
                <p><?=$advice->getDoctorResponse()?></p>
            </div>
        </div>
        <div class="clear"></div>
    </div><?
endif;