<?php
$form = $this->form;
/* @var $form RM_View_Form */
$view = Zend_Layout::getMvcInstance()->getView();
if ($form->getLangPanel()->isMultiLang()):
    $emptyForm = $form->getEmptyLangTemplate();
    $view->HeadScript()->captureStart();
        ?>LangsTabs = new Lang_Tabs();<?
    $view->HeadScript()->captureEnd();
endif;
?><form id="mainForm" action="<?=$view->url()?>" method="post" enctype="multipart/form-data">
    <table class="items edit-inside" width="100%" cellpadding="0" cellspacing="0">
        <tbody><?php
            echo $form->renderSimpleFields();
        ?></tbody>
    </table><?
    if ($form->getLangPanel()->isMultiLang()):
        ?><div id="tabs" class="ui-tabs ui-widget ui-widget-content ui-corner-all"><?
            echo $form->renderTranslation();
        ?></div><?
    endif;
    ?><div class="b-head">
        <table width="100%" cellpadding="0" cellspacing="0"><?
            echo $form->renderButtons();
        ?></table>
    </div>
</form><?php
?>