<?php
if ($this->user instanceof RM_User_Interface) :
    $menuHelper = new RM_View_Helper_Menu();
    echo $menuHelper->getMenuHTML($this->user, $this->menu, array(
        array(
            'name' => 'Города',
            'url' => $this->url(array(), 'admin-city-list'),
            'menu' => 'cities'
        ),
        array(
            'name' => 'Статические страницы',
            'subItems' => array(
                array(
                    'name' => 'Новости',
                    'url' => $this->url(array(), 'admin-news-list'),
                    'menu' => 'news'
                ),
                array(
                    'name' => 'Текстовые страницы',
                    'url' => $this->url(array(), 'admin-page-list'),
                    'menu' => 'pages'
                ),
                array(
                    'name' => 'Авторы',
                    'url' => $this->url(array(), 'admin-author-list'),
                    'menu' => 'authors'
                )
            )
        ),
        array(
            'name' => 'Опции страниц',
            'subItems' => array(
                array(
                    'name' => 'Теги',
                    'url' => $this->url(array(), 'admin-tag-list'),
                    'menu' => 'tags'
                )
            )
        ),
        array(
            'name' => 'Статические блоки',
            'subItems' => array(
                array(
                    'name' => 'Блоки',
                    'url' => $this->url(array(
                                'idPage' => 0,
                                'type' => RM_Block::TYPE_SIMPLE_NAME,
                                'page' => 1,
                                'searchType' => RM_Block::SEARCH_TYPE_BLOCK,
                                'textType' => RM_Content_Field_Process::PROCESS_TYPE_HTML
                            ), 'admin-block-list'),
                    'menu' => 'blocks'
                )
            )
        ),
        array(
            'name' => 'Баннеры',
            'url' => $this->url(array(), 'admin-banner-area-list'),
            'menu' => 'bannerAreas'
        ),
        array(
            'name' => 'Комментарии',
            'url' => $this->url(array(), 'admin-comment-list'),
            'menu' => 'comments'
        ),
        array(
            'name' => 'Пользователи',
            'url' => $this->url(array(), 'admin-user-index'),
            'menu' => 'users'
        ),
        array(
            'name' => 'Языки',
            'url' => $this->url(array(), 'admin-lang-index'),
            'menu' => 'lang'
        ),
        array(
            'name' => 'Найстройки',
            'url' => $this->url(array(), 'admin-settings-list'),
            'menu' => 'settings'
        ),
        array(
            'name' => 'Настройки программиста',
            'minRole' => RM_User_Role::HIERARCHY_PROGRAMMER,
            'subItems' => array(
                array(
                    'name' => 'Ошибки',
                    'url' => $this->url(array(), 'admin-error-categories-list'),
                    'menu' => 'error',
                    'count' => RM_Error::getNewErrorsCount()
                ),
                array(
                    'name' => 'Основные настройки',
                    'url' => $this->url(array(), 'admin-baseSettings-index'),
                    'menu' => 'main-settings'
                )
            )
        )
    ));
endif;