<?php
if ($this->user instanceof RM_User_Interface) :
    $menuHelper = new RM_View_Helper_Menu();
    echo $menuHelper->getMenuHTML($this->user, $this->menu, array(
        array(
            'name' => 'Медицинские услуги',
            'url' => $this->url(array(), 'admin-medical-service-list'),
            'menu' => 'medical-services'
        ),
        array(
            'name' => 'Медицинские должности',
            'url' => $this->url(array(), 'admin-medical-post-list'),
            'menu' => 'medical-posts'
        ),
        array(
            'name' => 'Медицинские советы',
            'url' => $this->url(array(), 'admin-medical-advice-list'),
            'menu' => 'medical-advices',
            'count' => (new Application_Model_Medical_Advice_Search())->getNotProcessedCount()
        ),
        array(
            'name' => 'Специалисты',
            'url' => $this->url(array(), 'admin-medical-doctor-list'),
            'menu' => 'medical-doctors'
        ),
        array(
            'name' => 'Заявки',
            'url' => $this->url(array(), 'admin-medical-reservation-list'),
            'menu' => 'reservations',
            'count' => (new Application_Model_Medical_Reservation_Search())->getNotProcessedCount()
        ),
        array(
            'name' => 'Текстовые блоки',
            'url' => $this->url(array(), 'admin-text-block-list'),
            'menu' => 'blocks'
        ),
        array(
            'name' => 'Баннеры',
            'url' => $this->url(array(), 'admin-banner-list'),
            'menu' => 'banners'
        ),
        array(
            'name' => 'Цитаты',
            'url' => $this->url(array(), 'admin-quote-list'),
            'menu' => 'quotes'
        ),
        array(
            'name' => 'Отзывы',
            'url' => $this->url(array(), 'admin-feedback-list'),
            'menu' => 'feedbacks',
            'count' => (new Application_Model_Feedback_Search())->getNotProcessedCount()
        ),
        array(
            'name' => 'Опции',
            'url' => $this->url(array(), 'admin-option-list'),
            'menu' => 'options'
        ),
        array(
            'name' => 'Пользователи',
            'url' => $this->url(array(), 'admin-user-index'),
            'menu' => 'users'
        ),
        array(
            'name' => 'Языки',
            'url' => $this->url(array(), 'admin-lang-index'),
            'menu' => 'lang'
        ),
        array(
            'name' => 'Настройки',
            'url' => $this->url(array(), 'admin-settings-list'),
            'menu' => 'settings'
        ),
        array(
            'name' => 'Настройки программиста',
            'minRole' => RM_User_Role::HIERARCHY_PROGRAMMER,
            'subItems' => array(
                array(
                    'name' => 'Ошибки',
                    'url' => $this->url(array(), 'admin-error-categories-list'),
                    'menu' => 'error',
                    'count' => RM_Error::getNewErrorsCount()
                ),
                array(
                    'name' => 'Основные настройки',
                    'url' => $this->url(array(), 'admin-baseSettings-index'),
                    'menu' => 'main-settings'
                )
            )
        )
    ));
endif;