<?php
use Application_Model_TextBlock as Block;
$aboutClinic = Block::getByAlias('about-clinic');
$vacancy = Block::getByAlias('opened-vacancies');
?><div class="clinic">
    <div class="fix">
        <div class="clinic-left-box"><?
            if ($aboutClinic instanceof Block) : ?>
                <div class="main-title"><?=$aboutClinic->getName()?></div>
                <div class="clinic-text-box"><?=$aboutClinic->getText()?></div><?
            endif
            ?><div class="clinic-quote">
                <div class="clinic-quote-text">
                    <i class="ico quote-top-s-ico"></i>
                    <div class="simple-text">
                        <p>
                            Мы так хотели запустит сайт к новому году, что забыли о выходных.
                        </p>
                    </div>
                    <i class="ico quote-bottom-s-ico"></i>
                </div>
                <div class="quote-text-sign">— Илья Сергеевич</div>
            </div>
        </div><?
        if ($vacancy instanceof Block) : ?>
            <div class="clinic-right-box">
                <div class="main-title"><?=$vacancy->getName()?></div>
                <div class="clinic-text-box"><?=$vacancy->getText()?></div>
            </div><?
        endif
        ?><div class="clear"></div>
        <?=$this->render('blocks/index/parts/banner.phtml')?>
        <div class="doctor-box"><?
            foreach ($this->doctors as $doctor) :
                echo $this->partial('blocks/clinic/doctor.phtml', array(
                    'doctor' => $doctor
                ));
            endforeach
        ?></div>
        <div class="clinic-comments">
            <div class="fix">
                <div class="main-title">Отзывы</div>
                <div class="comments-item-list">
                    <div class="comments-item">
                        <div class="comments-item-author">
                            <div class="comments-item-author-name">Коляновна</div>
                            <div class="comments-item-author-post">28 января 2014</div>
                        </div>
                        <div class="comments-item-text">
                            <div class="simple-text">
                                <p>Достаточно чистить зубы два-три раза в день и использовать для чистки зубную нить. Ополаскиватель для рта также иммеет хорошие рекомендации.</p>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="comment-btn-box">
                    <a class="button comments-btn" href="#">Напиcать отзыв...</a>
                    <div class="popup-box up-show">
                        <i class="ico popup-tile"></i>
                        <div class="popup-client-box">
                            <div class="popup-client-box-item">
                                <input type="text" placeholder="Имя"/>
                            </div>
                            <div class="popup-client-box-item">
                                <input type="text" placeholder="Телефон"/>
                            </div>
                            <textarea></textarea>
                            <div class="popup-client-box-item">
                                <input class="button popup-send-btn" type="button" value="Записатся"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-thx">Благодарим вас. <br/> Отзыв будет опубликован через 1—2 дня.</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>