<?php
use Application_Model_TextBlock as Block;
$aboutClinic = Block::getByAlias('about-clinic');
$vacancy = Block::getByAlias('opened-vacancies');
?><div class="clinic">
    <div class="fix">
        <div class="clinic-left-box"><?
            if ($aboutClinic instanceof Block) : ?>
                <div class="main-title"><?=$aboutClinic->getName()?></div>
                <div class="clinic-text-box"><?=$aboutClinic->getText()?></div><?
            endif;
            foreach ($this->quotes as $quote) :
                echo $this->partial('blocks/clinic/quote.phtml', array(
                    'quote' => $quote
                ));
            endforeach
        ?></div><?
        if ($vacancy instanceof Block) : ?>
            <div class="clinic-right-box">
                <div class="main-title"><?=$vacancy->getName()?></div>
                <div class="clinic-text-box"><?=$vacancy->getText()?></div>
            </div><?
        endif
        ?><div class="clear"></div>
        <?=$this->render('blocks/index/parts/banner.phtml')?>
        <div class="doctor-box"><?
            foreach ($this->doctors as $doctor) :
                echo $this->partial('blocks/clinic/doctor.phtml', array(
                    'doctor' => $doctor
                ));
            endforeach
        ?></div>
        <div class="clinic-comments">
            <div class="fix">
                <div class="main-title">Отзывы</div>
                <div class="comments-item-list"><?
                    foreach ($this->feedbacks as $feedback) :
                        echo $this->partial('blocks/clinic/feedback.phtml', array(
                            'feedback' => $feedback
                        ));
                    endforeach
                ?></div>
                <div class="comment-btn-box">
                    <span id="form-activate-button" class="button comments-btn">Напиcать отзыв...</span>
                    <div id="form-container" class="popup-box up-show" style="display: none">
                        <i class="ico popup-tile"></i>
                        <form action="">
                            <div class="popup-client-box">
                                <div class="popup-client-box-item">
                                    <input id="visitor-name" name="visitor-name" data-alias="visitor_name" type="text" placeholder="Имя"/>
                                </div>
                                <div class="popup-client-box-item">
                                    <input id="visitor-phone" name="visitor-phone" data-alias="visitor_phone" type="text" placeholder="Телефон для связи"/>
                                </div>
                                <div><textarea id="visitor-feedback" name="visitor-feedback" data-alias="visitor_feedback"></textarea></div>
                                <div class="popup-client-box-item">
                                    <input id="form-submit-button" class="button popup-send-btn" type="button" value="Отправить"/>
                                </div>
                            </div>
                        </form>
                        <div id="error-box" class="popup-client-box" style="display: none">
                            <span class="error-message"></span>
                            <span id="form-try-again-button">Попробовать еще раз</span>
                        </div>
                    </div>
                </div>
                <div id="thank-you-box" class="popup-thx" style="display: none">Благодарим вас. <br/> Отзыв будет опубликован через 1—2 дня.</div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div><?
echo $this->headScript()->captureStart();
?>$(function() {
    Med.SimplePopupForm.init('<?=$this->url([], 'post-feedback-ajax')?>', {
        "name": '#visitor-name',
        "phone": '#visitor-phone',
        "text": '#visitor-feedback'
    });
});<?
echo $this->headScript()->captureEnd();