<div class="jobs">
    <div class="fix">
        <div class="jobs-item">
            <p class="main-title">Вакансии</p>
            <p class="jobs-item-text">Отправить резюме на <a href="mailto:medoptima-s@yandex.ru">medoptima-s@yandex.ru</a></p>
        </div>
        <div class="jobs-item">
            <p class="main-title">Ортопед</p>
            <p class="jobs-item-text">Ждём опытного ортопеда в гости на чай с плюшками. Расскажем-покажем, плохому научим</p>
        </div>
        <div class="jobs-item">
            <p class="main-title">Терапевт стажёр</p>
            <p class="jobs-item-text">Принимаем на работу стажёров. Научим, расскажем, покажем. Сразу после меда или небольшой практикой</p>
        </div>
    </div>
</div>