<?php
$previewWidth = null;  //RM_TODO size of previews
$previewHeight = null;
$width = 1020;
$height = 480;
$banners = $this->banners;
foreach ($banners as $key => &$banner) {
    /** @var Application_Model_Banner $banner */
    if ( $banner->getPhoto() ) {
        $banner = array(
            'photoUrl' => $banner->getPhoto()->getPath($width, $height),
            'previewPhotoUrl' => $banner->getPhoto()->getPath($previewWidth, $previewHeight),
            'banner' => $banner
        );
    } else {
        unset($banners[$key]);
    }
}
?><div class="banner">
    <div class="banner-box">
        <div class="connected-carousels">
            <div class="stage">
                <div class="carousel carousel-stage">
                    <ul><?
                    foreach ($banners as $data) : ?>
                        <li><?
                            echo $this->partial('blocks/index/parts/banner-parts/quote.phtml', array(
                                    'banner' => $data['banner']
                                ));
                            ?><img src="<?=$data['photoUrl']?>" width="<?=$width?>" height="<?=$height?>" alt="">
                        </li><?
                    endforeach
                    ?></ul>
                </div>
                <a href="#" class="prev prev-stage"><span><i class="ico banner-prev-ico"></i></span></a>
                <a href="#" class="next next-stage"><span><i class="ico banner-next-ico"></i></span></a>
            </div>
            <div class="navigation">
                <div class="carousel carousel-navigation">
                    <ul><?
                    foreach ($banners as $data) : ?>
                        <li><img src="<?=$data['photoUrl']?>" width="<?=$previewWidth?>" height="<?=$previewHeight?>" alt=""></li><?
                    endforeach
                    ?></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div>