<div class="banner">
    <div class="banner-box">
        <div class="connected-carousels">
            <div class="stage">
                <div class="carousel carousel-stage">
                    <ul>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img2.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img3.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img4.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img5.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img6.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" width="1020" height="480" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" width="1020" height="480" alt=""></li>
                    </ul>
                </div>
                <div class="photo-text-box">
                    <span class="photo-text-box-title">Воспользуйтесь записью на сайте. Я проконсультирую вас бесплатно.</span>
                    <div class="photo-text-box-sign">
                        <span class="photo-text-box-doctor-name">— Илья Сергеевич</span>
                        <div class="clear"></div>
                        <span class="photo-text-box-doctor-status">главный врач</span>
                    </div>
                </div>
                <a href="#" class="prev prev-stage"><span><i class="ico banner-prev-ico"></i></span></a>
                <a href="#" class="next next-stage"><span><i class="ico banner-next-ico"></i></span></a>
            </div>
            <div class="navigation">
                <div class="carousel carousel-navigation">
                    <ul>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img2.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img3.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img4.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img5.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img6.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" alt=""></li>
                        <li><img src="http://sorgalla.com/jcarousel/examples/_shared/img/img1.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
</div><?php
$this->headScript()->appendFile(
    '/s/public/js/lib/jcarousel.connected-carousels.js');