<div class="index-text-box">
    <div class="index-quote">
        <div class="index-quote-text">
            <i class="ico quote-top-ico"></i>
            <div class="simple-text">
                <p>
                    Один, гад такой, взял и выдрал мне зуб. Сразу написала отзыв на сайте.
                    На следующий день позвонил главный врач, хороший такой с манерами. Вставили бесплатно коронку,
                    угостили чаем.
                </p>
            </div>
            <i class="ico quote-bottom-ico"></i>
        </div>
        <div class="quote-text-sign">— Наталья Матвеевна</div>
        <div class="clear"></div>
    </div>
    <div class="text-box-item">
        <div class="simple-text">
            <h3>Как долго делается коронка?</h3>
            <p>
                На первом приёме врач-ортодонт делает слепок пациенту.
                Слепок передаётся технику, который изготавливает коронку. Весь процесс занимает 4—7 дней. В этот промежуток, пацтиент выбирает — ходить без зуба
                или поставить временную пломбу. Готовую коронку одевают на следующем приёме, подтачивают детали. Процесс вставки безболезненный.
            </p>
            <img src="/s/public/images/text-img-1.png" alt=""/>
            <img src="/s/public/images/text-img-2.png" alt=""/>
            <img src="/s/public/images/text-img-3.png" alt=""/>
        </div>
        <div class="clear"></div>
    </div>
</div>