<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$form
    ->add( (new RM_View_Form_Field_Text('Имя посетителя', 'visitor_name', ''))->disable() )
    ->add( (new RM_View_Form_Field_Text('Телефон посетителя', 'visitor_phone', ''))->disable() )
    ->add( (new RM_View_Form_Field_Textarea('Отзыв', 'feedback_content', ''))->disable() )
    ->add( (new RM_View_Form_Field_Text('Дата', 'date_posted', ''))->disable() );
echo $form->render();