<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$form
    ->add( new RM_View_Form_Field_Text('Имя посетителя', 'visitor_name', '') )
    ->add( new RM_View_Form_Field_Text('Телефон посетителя', 'visitor_phone', '') )
    ->add( new RM_View_Form_Field_Textarea('Отзыв', 'feedback_content', '') )
    ->add( new RM_View_Form_Field_Text('Дата', 'date_posted', '') )
    ->add( new RM_View_Form_Field_Checkbox('Отображать на главной', 'show_on_main', false) );
echo $form->render();