<?php
	echo $this->doctype();
?><html>
    <head><?
        echo $this->headMeta();
        echo $this->headTitle();
        echo $this->headLink();
        echo $this->headStyle();
        echo $this->render('blocks/social/og.phtml');
        echo $this->render('blocks/paginator/relations.phtml');
        ?><!--[if lt IE 9]>
            <script type="text/javascript" src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrapper"><?
            echo $this->render('blocks/elements/header.phtml');
            echo $this->layout()->content;
            ?><div class="h-footer"></div>
        </div><?
        echo $this->render('blocks/elements/footer.phtml');
        ?><script type="text/javascript" src="<?=$this->url(array(), 'translation')?>"></script>
        <script type="text/javascript">
            var config = {
                "phoneRegex": <?=Zend_Registry::get('cfg')['validation']['regex']['phone']?>,
                "phoneMask": '<?=Zend_Registry::get('cfg')['validation']['mask']['phone']?>'
            };
        </script><?
        echo $this->render('blocks/index/reservation/doctor.ejs');
        echo $this->render('blocks/index/calendar/date.ejs');
        echo $this->headScript();
        echo $this->render('blocks/loader/ajax.phtml');
    ?></body>
</html>
