<?=$this->doctype()?><html>
<head>
	<link rel="icon" type="image/vnd.microsoft.icon" href="/favicon.ico">
	<link rel="SHORTCUT ICON" href="/favicon.ico"><?php
		echo $this->headMeta();
		echo $this->headTitle();
?></head>
<body>
<div class="body-bg"></div>
<div class="body-decor"></div>
    <script type="text/javascript" src="/s/public/js/lib/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="/s/public/js/lib/ext.js"></script>
    <script type="text/javascript" src="/s/public/js/restoran.js"></script>
    <script type="text/javascript" src="/s/public/js/social/window.js"></script>
    <script type="text/javascript" src="<?=$this->url(array(), 'translation')?>"></script>
    <script type="text/javascript">
        var MODAL = true;<?
        if ($this->error) :
            ?>R.window.error('<?=$this->error?>');<?
        endif;
        if ($this->facebookConnected === true) :
            ?>R.window.fbConnected('<?=$this->account->getUserEmail()?>');<?
        endif;
        if ($this->vkontakteConnected === true) :
            ?>R.window.vkConnected('<?=$this->account->getUserEmail()?>');<?
        endif;
        if ($this->vkCreate === true) :
            ?>R.window.vkCreate('<?=$this->code?>');<?
        endif;
        if ($this->toAccount === true) :
            ?>R.window.to('<?=$this->url(array(), 'profile')?>');<?
        elseif ($this->toLogin === true) :
            ?>R.window.to('<?=$this->url(array(), 'login')?>');<?
        endif;
        ?>R.window.close();<?
    ?></script>
</body>
</html>
