<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();
$form
    ->add(new RM_View_Form_Field_Text('Баннерная ссылка', 'banner_link', ''))
    ->add(new RM_View_Form_Field_Image('Фотография', 'id_photo', 0, 200, 150))
    ->add(new RM_View_Form_Field_Checkbox('Показывать в новой вкладке', 'show_in_new_tab', 0))
    ->add(new RM_View_Form_Field_Image('Фотография (локализации)', 'id_locale_photo', [], 200, 150))
    ->add(new RM_View_Form_Field_Text('Ссылка (локализации)', 'localeBannerLink', []))
    ->add(new RM_View_Form_Field_Text('Название (системное)', 'name', array()))
    ->add(new RM_View_Form_Field_Text('Название (отображается)', 'displayName', array()))
    ->add(new RM_View_Form_Field_Textarea('Описание банера', 'displayText', array()));
echo $form->render();
