<?php
$table = new RM_View_Table();
$table
        ->setEditRoute($this->editRoute)
        ->setStatusUrl($this->ajaxUrl)
        ->setHead('Название', 'На главной', 'На странице клиники')
        ->setSortable();

foreach ($this->banners as $banner) :
    /* @var $banner Application_Model_Banner */
    $row = $table
        ->addRecord($banner->getId(), $banner->getName())
        ->addTd($banner->isShownOnMain() ? 'Да' : 'Нет')
        ->addTd($banner->isShownOnClinic() ? 'Да' : 'Нет')
        ->setStatus($banner->getStatus())
        ->setPosition($banner->getPosition())
        ->setHideble()
        ->setDeletable();
endforeach;
echo $table;