<div class="calendar-appointment">
    <div class="calendar-appointment-date"><span>31</span> дек в <span>17:45</span></div>
    <div class="calendar-appointment-text"><span>Татьяна</span> позвонит на ваш номер через 30 минут для уточнения деталей.</div>
    <div href="#" class="calendar-appointment-link"><a href="#">Отменить заявку</a></div>
</div>

<div class="calendar-appointment">
    <div class="calendar-appointment-date">Отмена <span>31</span> дек в <span>17:45</span></div>
    <div class="calendar-appointment-text">Вы отменили запись. Если вы сомневаетесь — позвоните нам 47-77-88 или напишите <a href="#">medoptima-s@yandex.ru</a></div>
    <div href="#" class="calendar-appointment-link"><a href="#">Вернуть запись</a></div>
</div>