<div id="reservation-widget" class="calendar">
    <div class="calendar-title">Запись на прием</div>
    <div class="calendar-data-container">
        <div class="calendar-prev-month-link"><i class="ico prev-month-link-ico"></i><span>Июль</span></div>
        <div id="calendar" class="calendar-box"></div>
        <div class="calendar-next-month-link"><i class="ico next-month-link-ico"></i><span>Сентябрь</span></div>
    </div>
    <?= $this->render('blocks/index/parts/calendar/popup.phtml') ?>
    <!--    --><? //=$this->partial('blocks/index/parts/calendar/appointment.phtml')?>
</div>
