<div class="calendar">
    <div class="calendar-title">Запись на прием</div>
    <div class="calendar-data-container hidden">
        <div class="calendar-prev-month-link"><i class="ico prev-month-link-ico"></i><span>Июль</span></div>
        <div class="calendar-box">
            <div class="calendar-box-month-title">Август 2013</div>
            <div class="calendar-box-week-title">
                <div class="calendar-box-week-date">Пн</div>
                <div class="calendar-box-week-date">Вт</div>
                <div class="calendar-box-week-date">Ср</div>
                <div class="calendar-box-week-date">Чт</div>
                <div class="calendar-box-week-date">Пт</div>
                <div class="calendar-box-week-date">Сб</div>
                <div class="calendar-box-week-date off-week-date">Вс</div>
                <div class="clear"></div>
            </div>
            <div class="calendar-box-date">
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">29</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">30</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">31</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">1</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">2</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">3</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">4</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">5</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">6</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">7</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">8</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">9</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">10</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">11</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">12</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">13</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">14</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">15</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">16</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">17</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">18</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">19</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">20</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">21</span>
                </div>
                <div class="calendar-box-date-item">
                    <span class="calendar-box-date-item-value">22</span>
                </div>
                <div class="calendar-box-date-item current-date">
                    <span class="calendar-box-date-item-value">23</span>
                </div>
                <div class="calendar-box-date-item active-date">
                    <span class="calendar-box-date-item-value">24</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">25</span>
                </div>
                <div class="calendar-box-date-item active-date clicked">
                    <span class="calendar-box-date-item-value">26</span>
                    <?= $this->partial('blocks/index/parts/calendar/popup.phtml') ?>
                </div>
                <div class="calendar-box-date-item active-date">
                    <span class="calendar-box-date-item-value">27</span>
                </div>
                <div class="calendar-box-date-item active-date">
                    <span class="calendar-box-date-item-value">28</span>
                </div>
                <div class="calendar-box-date-item active-date">
                    <span class="calendar-box-date-item-value">29</span>
                </div>
                <div class="calendar-box-date-item active-date">
                    <span class="calendar-box-date-item-value">30</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">1</span>
                </div>
                <div class="calendar-box-date-item off-date">
                    <span class="calendar-box-date-item-value">2</span>
                </div>
                <div class="clear"></div>
            </div>
            <div class="calendar-current-day-link"><span>Сегодня</span></div>
        </div>
        <div class="calendar-next-month-link"><i class="ico next-month-link-ico"></i><span>Сентябрь</span></div>
    </div>
    <?=$this->partial('blocks/index/parts/calendar/appointment.phtml')?>
</div>

