<div class="calendar-popup">
    <i class="ico popup-tile"></i>
    <div class="calendar-popup-box">
        <div class="calendar-popup-box-menu">
            <button class="popup-btn">Удалить</button>
            <button class="popup-btn clicked">Вылечить</button>
            <button class="popup-btn">Отбелить</button>
            <button class="popup-btn">Узнать</button>
            <button class="popup-btn clicked">Вставить</button>
            <button class="popup-btn">Другое</button>
            <div class="clear"></div>
        </div>
        <div class="popup-doctors-box">
            <?=$this->partial('blocks/index/parts/calendar/popup-item.phtml',array(
                'itemStatus'=>'activated'
            ));?>
            <?=$this->partial('blocks/index/parts/calendar/popup-item.phtml');?>
            <?=$this->partial('blocks/index/parts/calendar/popup-item.phtml');?>
            <?=$this->partial('blocks/index/parts/calendar/popup-item.phtml');?>
            <?=$this->partial('blocks/index/parts/calendar/popup-item.phtml');?>
            <div class="clear"></div>
        </div>
        <div class="popup-client-box">
            <div class="popup-client-box-item">
                <input type="text" placeholder="Имя"/>
            </div>
            <div class="popup-client-box-item">
                <input type="text" placeholder="Телефон"/>
            </div>
            <div class="popup-client-box-item">
                <input class="button popup-send-btn" type="button" value="Записатся"/>
            </div>
        </div>
    </div>
</div>