<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();
$form
    ->add(new RM_View_Form_Field_Text('Url', 'url', ''))
    ->add(new RM_View_Form_Field_Text('Заголовок страницы', 'pageTitle', array()))
    ->add(new RM_View_Form_Field_Text('Описание страницы', 'pageDesc', array()))
    ->add(new RM_View_Form_Field_Text('Ключевые слова', 'pageKeywords', array()))
    ->add(new RM_View_Form_Field_Text('Название страницы', 'name', array()))
    ->add(new RM_View_Form_Field_Text('СЕО заголовок', 'seoTitle', array()))
    ->add(new RM_View_Form_Field_Editor('СЕО текст', 'seoText', array()));
if ($this->action) {
    $action = new RM_View_Form_Field_Text('Controller action', '', $this->action);
    $form->add($action->disable());
}
echo $form->render();