<?php
$table = new RM_View_Table();

$table
    ->setEditRoute($this->editRoute)
    ->setStatusUrl($this->ajaxUrl)
    ->setHead('Название страницы')
    ->addPaginator($this->pages);

foreach ($this->pages as $page) :
    /* @var Application_Model_Page $page */
    $row = $table
        ->addRecord($page->getId(), $page->getContent()->getName())
        ->setPreviewUrl($page->getRoute()->getUrl());
    if (!$page->isSystem()) :
        $row->setStatus($page->getStatus())
            ->setHideble()
            ->setDeletable();
    endif;
endforeach;

echo $table;