<?php
use Application_Model_Banner as Banner;

/* @var Banner $banner */
$banner = $this->banner;

if ($banner instanceof Banner && $banner->hasQuote()) :
    ?><div class="photo-text-box">
        <span class="photo-text-box-title"><?=$banner->getQuote()->getText()?></span>
        <div class="photo-text-box-sign">
            <span class="photo-text-box-doctor-name">— <?=$banner->getQuote()->getAuthor()?></span>
            <div class="clear"></div>
            <span class="photo-text-box-doctor-status"><?=$banner->getQuote()->getAuthorPost()?></span>
        </div>
    </div><?
endif;