<?php
$cfg = Zend_Registry::get('cfg');
$url = $this->url(array(
    'code' => $this->code->getCode()
), 'password-recovery');
?>Вы подали заявку на восстановление пароля на сайте AzRestoran.<br/><?
?>Ваш новый пароль – <?=$this->code->getPassword()?><br/><?
?>Для активации нового пароля перейдите по <a href="http://<?=$cfg['domain']?><?=$url?>">ссылке</a><br/>
<br/><?
?>С наилучшими пожеланиями,<br/>
<a href="http://<?=$cfg['domain']?>">AzRestoran</a><br/>