<div class="footer">
    <div class="fix">
        <div class="footer-copyright"> © Мед оптима 2014. Все права защищены</div>
        <div class="contact-info">
            <div class="contact-info-phone-num">
                <span class="phone-num-value"><span><?=$this->phonePrefix
                        ?></span><?=$this->phoneWithoutPrefix?></span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>