<div class="header">
    <div class="fix">
        <div class="header-logo">
            <div class="header-logo-img-container">
                <img src="/s/public/images/header-logo.png" alt="Мед Оптима" width="170" height="100"/>
            </div>
        </div>
        <?=$this->render('blocks/elements/header-parts/menu.phtml')?>
        <div class="contact-info">
            <div class="contact-info-phone-num">
                <span class="phone-num-value"><span><?=$this->phonePrefix
                        ?></span><?=$this->phoneWithoutPrefix?></span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>