<div class="header">
    <div class="fix">
        <div class="header-logo">
            <div class="header-logo-img-container"><?
                $isIndex = $this->currentMenuAlias === 'index';
                echo $isIndex ? '<span>' : '<a href="' . $this->url([], 'index') . '">';
                ?><img src="/s/public/images/header-logo.png" alt="Мед Оптима" width="170" height="100"/><?
                echo $isIndex ? '</span>' : '</a>';
            ?></div>
        </div>
        <?=$this->render('blocks/elements/header-parts/menu.phtml')?>
        <div class="contact-info">
            <div class="contact-info-phone-num">
                <span class="phone-num-value"><span><?=$this->phonePrefix
                        ?></span><?=$this->phoneWithoutPrefix?></span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>