<div class="header">
    <div class="fix">
        <div class="header-logo">
            <div class="header-logo-img-container">
                <img src="/s/public/images/header-logo.png" alt="Мед Оптима" width="170" height="100"/>
            </div>
        </div>
        <ul class="header-menu">
            <li class="current">
                <a href="#">Главная</a>
            </li>
            <li>
                <a href="#">Клиника</a>
            </li>
            <li>
                <a href="#">Советы</a>
            </li>
            <li>
                <a href="#">Контактная информация</a>
            </li>
        </ul>
        <div class="contact-info">
            <div class="contact-info-phone-num">
                <span class="phone-num-value"><span>(8452)</span>44-77-88</span>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>