<div id="message-save-success" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label">31 декабря в 17:45</span></div>
    <div class="calendar-appointment-text"><span>Татьяна</span> позвонит на ваш номер через 30 минут для уточнения деталей.</div>
    <div class="calendar-appointment-link"><a href="#">Отменить заявку</a></div>
</div>

<div id="message-error" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label">Произошла ошибка</span></div>
    <div class="calendar-appointment-text">Во время операции произошла ошибка. Попробуйте еще раз</a></div>
</div>

<div id="message-remove-success" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label">Отмена 31 декабря в 17:45</span></div>
    <div class="calendar-appointment-text">Вы отменили запись. Если вы сомневаетесь — позвоните нам 47-77-88 или
        напишите <a href="#">medoptima-s@yandex.ru</a></div>
    <div class="calendar-appointment-link"><a href="#">Вернуть запись</a></div>
</div>

<div id="message-loader" class="calendar-appointment" style="display: none"></div>