<div id="message-create" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label"></span></div>
    <div class="calendar-appointment-text">Администратор свяжется с вами для уточнения деталей.</div>
    <div class="calendar-appointment-link"><a class="message-button" href="javascript:void(0)">Записаться на другое время</a></div>
    <div class="calendar-appointment-link"><a class="message-button" href="javascript:void(0)">Отменить заявку</a></div>
</div>

<div id="message-error" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label">Произошла ошибка</span></div>
    <div class="calendar-appointment-text">Во время операции произошла ошибка. Попробуйте еще раз</a></div>
</div>

<div id="message-delete" class="calendar-appointment" style="display: none">
    <div class="calendar-appointment-date"><span class="message-label"></span></div>
    <div class="calendar-appointment-text">Вы отменили запись. Если вы сомневаетесь — позвоните нам <br>(<?=$this->phonePrefix?>) <?=$this->phoneWithoutPrefix?> или
        напишите <br><a href="mailto:<?=$this->email?>"><?= $this->email ?></a>
    </div>
    <div class="calendar-appointment-link"><a class="message-button" href="javascript:void(0)">Вернуть запись</a></div>
</div>

<div id="message-loader" class="calendar-appointment" style="display: none"></div>