<?php
$fullWidth = 1020;
$fullHeight = 480;

$previewWidth = 160;
$previewHeight = 80;

/* @var Application_Model_Banner[] $banners */
$banners = $this->banners;
$showQuotes = isset($this->showQuotes) ? $this->showQuotes : true;
?><div class="banner<?=$this->withMargin?>">
    <div class="banner-box">
        <div class="connected-carousels">

            <div class="stage">
                <div class="carousel carousel-stage">
                    <ul><?
                        foreach ($banners as $banner) :
                            ?><li><?
                                $imagePath = $banner->getPhoto()->getPath($fullWidth, $fullHeight);
                                if ($showQuotes) :
                                    echo $this->partial('blocks/index/banner/quote.phtml', ['banner' => $banner]);
                                endif;
                                ?><img src="<?=$imagePath?>" width="<?=$fullWidth?>" height="<?=$fullHeight?>" alt=""/>
                            </li><?
                        endforeach
                    ?></ul>
                </div>
                <a href="#" class="prev prev-stage"><span><i class="ico banner-prev-ico"></i></span></a>
                <a href="#" class="next next-stage"><span><i class="ico banner-next-ico"></i></span></a>
            </div>

            <div class="navigation">
                <div class="carousel carousel-navigation">
                    <ul><?
                        foreach ($banners as $banner) :
                            $previewImagePath = $banner->getPhoto()->getPath($previewWidth, $previewHeight);
                            ?><li>
                                <img src="<?=$previewImagePath?>" width="<?=$previewWidth?>" height="<?=$previewHeight?>" alt=""/>
                            </li><?
                        endforeach
                    ?></ul>
                </div>
            </div>

        </div>
    </div>
    <div class="clear"></div>
</div>