<div class="index-text-box"><?
    foreach ($this->feedbacks as $feedback) :
        echo $this->partial('blocks/index/feedback.phtml', array(
            'feedback' => $feedback
        ));
    endforeach;
    $block = Application_Model_TextBlock::getByAlias('index');
    ?><div class="text-box-item">
        <div class="simple-text"><?
        if ($block instanceof Application_Model_TextBlock) :
            echo $block->getText();
        endif;
            ?><img src="/s/public/images/text-img-1.png" alt=""/>
            <img src="/s/public/images/text-img-2.png" alt=""/>
            <img src="/s/public/images/text-img-3.png" alt=""/>
        </div>
        <div class="clear"></div>
    </div>
</div>