<div class="index-text-box"><?
    foreach ($this->feedbacks as $feedback) :
        echo $this->partial('blocks/index/feedback.phtml', array(
            'feedback' => $feedback
        ));
    endforeach;
    $advice = (new Application_Model_Medical_Advice_Search_Repository())->getShownOnMainAdvice();
    if ($advice instanceof Application_Model_Medical_Advice) :
        ?><div class="text-box-item">
            <div class="simple-text">
                <h3><?=$advice->getVisitorQuestion()?></h3>
                <p><?= $advice->getDoctorResponse()?></p><?
                    foreach ($advice->getGallery()->getPhotos() as $photo) :
                        ?><img src="<?= $photo->getPath(140, 140) ?>" alt=""/><?
                    endforeach;
                ?></div>
            <div class="clear"></div>
        </div><?
    endif;
?></div>