<?
echo $this->partial('blocks/top.phtml');
$this->headScript()->captureStart(); 
?>$(function(){
	$('a').click(function(){
		var e = $(this);
		var action = e.attr('data-action');
		e.removeAttr('data-action');
		if (action) {
			var name = e.html();
			e.html('Processing...');
			$.ajax({
				url: "<?=$this->url(array(), 'admin-settings-clear')?>",
				type: "POST",
				data: 'type=' + action,
				success: function(result) {
					e.html(name + ' (Done)');
				}
			});
		}
	});
});<?php
$this->headScript()->captureEnd(); 
?><ul id="settingsList">
	<li><a href="javascript:void(0);" data-action="route">Clear cache</a></li>
	<li><a href="javascript:void(0);" data-action="image">Clear imagecache</a></li>
</ul>