<?php
$desc = 'Content block';
$name = 'content';
$value = array();
switch ($this->textType):
	case RM_Content_Field_Process::PROCESS_TYPE_HTML:
		$input = new RM_View_Form_Field_Editor($desc, $name, $value);
		break;
	case RM_Content_Field_Process::PROCESS_TYPE_TEXT:
        $input = new RM_View_Form_Field_Textarea($desc, $name, $value);
		break;
    case RM_Content_Field_Process::PROCESS_TYPE_LINE:
    default:
        $input = new RM_View_Form_Field_Text($desc, $name, $value);
		break;
endswitch;

$form = new RM_View_Form();
$form->getLangPanel()->allLangs();
$form
    ->add( new RM_View_Form_Field_Text(
        'Content block name',
        'name',
        $this->type === RM_Block::TYPE_SIMPLE_NAME ? '' : array()
    ) )
    ->add($input);
echo $form->render();

