<?php
$table = new RM_View_Table();
$table->setEditRoute('admin-block-edit')
    ->setStatusUrl($this->ajaxUrl)
    ->setHead('Block name')
    ->addPaginator($this->blocks);
foreach ($this->blocks as $block):
    /* @var Application_Model_Block $block */
    $row = $table
        ->addRecord($block->getId(), $block->getName())
        ->setStatus($block->getStatus())
        ->setHideble()
        ->setDeletable();
endforeach;
echo $table;