var _tr = {
    enterName : "Введите имя",
    nameTooShort : "Имя слишком короткое",
    nameTooLong : "Имя слишком длинное",
    phoneFormat : "Формат: +7(999)999-99-99",
    enterPhone : "Введите телефон",
    enterEmail : "Введите электронную почту",
    enterText : "Введите сообщение",
    textTooShort : "Сообщение слишком короткое",
    textTooLong : "Сообщение слишком длинное",
    unknownError : "Произошла неизвестная ошибка. Попробуйте еще раз"
};