<?php
if ($this->table->hasAjaxElements()):
    $view = Zend_Layout::getMvcInstance()->getView();
    $view->HeadScript()->captureStart();
    ?>Adminka.ItemsList().setAjaxUrl('<?=$this->table->getStatusUrl()?>');<?
    if ($this->table->isSortable()):
        ?>Adminka.ItemsListSort(<?=$this->table->getMinPosition()?>);<?php
    endif;
    $view->HeadScript()->captureEnd();
endif;
?><table id="itemsList" class="items list-item" width="100%" cellpadding="0" cellspacing="0">
    <thead><?=$this->table->renderThead()?></thead>
    <tbody><?=$this->table->renderTbody()?></tbody>
</table><?php
if ($this->table->hasFooter()):
    ?><div class="b-head"><?php
    if ($this->table->hasPaginator()):
        echo $this->table->renderPaginator();
    endif;
    ?><div class="clear"></div><?php
    ?></div><?php
endif;
?>