<div class="contacts">
    <div class="main-title">Контактная информация</div>
    <div class="contact-box">
        <div class="contact-box-phone">(8452) 47-77-88</div>
        <div class="contact-box-mail">
            <a href="mailto:medoptima-s@yandex.ru">medoptima-s@yandex.ru</a>
        </div>
        <div class="contact-box-adress">улица Тархова 39, Саратов, Россия, 162539</div>
    </div>
    <div class="contact-box-sign">
        <div class="simple-text">
            <h3> Остановки «6-ой микрорайон»:</h3>
            <ul>
                <li>— 8-я маршрутка;</li>
                <li>— 74-й автобус;</li>
            </ul>
            <p>и «ул. Топольчанская» — 53-й автобус.</p>
        </div>
    </div>
    <div class="clear"></div>
</div>