<?php
$table = new RM_View_Table();
$table->setEditRoute($this->editRoute)
    ->setStatusUrl($this->ajaxUrl)
    ->setHead('Name', 'Alias')
    ->addPaginator($this->bannerAreas);
foreach ($this->bannerAreas as $bannerArea) :
    /* @var Application_Model_Banner_Area $bannerArea */
    $table->addRecord($bannerArea->getId(), $this->createLink($bannerArea->getName(), $this->url(array(
        'idBannerArea' => $bannerArea->getId(),
    ), 'admin-banner-list')))
        ->addTd($bannerArea->getAlias())
        ->setStatus($bannerArea->getStatus())
        ->setDeletable();
endforeach;
echo $table;