<?php
    $view = Zend_Layout::getMvcInstance()->getView();
	array_unshift(
		$this->crumbs,
		array(
            $view->translate->_('Главная'),
            $this->url(array(
                'city-alias' => $view->city->getAlias()
            ), 'index')
        )
	);
?><div class="breadcrumbs"><?
	$count = sizeof($this->crumbs);
	$i = 0;
	foreach ($this->crumbs as $crumb):
		++$i;
        if ($i !== $count):
            ?><div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
                <a class="link-to" itemprop="url" href="<?=$crumb[1]?>"><?
        endif;
                    ?><span <?
                        if ($count === $i):
                            ?>class="current"<?
                        else:
                            ?> itemprop="title"<?
                        endif;
                    ?>><?
                        echo $crumb[0];
                    ?></span><?
        if ($count !== $i):
                ?></a> —
            </div><?
        endif;
	endforeach;
    ?><div class="clear"></div>
</div>