<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$form
    ->add(new RM_View_Form_Field_Text('Имя посетителя', 'visitor_name', ''))
    ->add(new RM_View_Form_Field_Text('Email посетителя', 'visitor_email', ''))
    ->add(new RM_View_Form_Field_Textarea('Вопрос', 'question', ''))
    ->add(new RM_View_Form_Field_Textarea('Ответ', 'response', ''))
    ->add(new RM_View_Form_Field_Select('Кто ответил', 'id_doctor',
        array(0 => 'Отсутствует') + $this->toSelect(
        Application_Model_Medical_Doctor::getList()
    )))
    ->add(new RM_View_Form_Field_Checkbox('Отображать на главной', 'shown_on_main', false));

echo $form->render();