<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$form
    ->add(new RM_View_Form_Field_Editor('Вопрос', 'question', ''))
    ->add(new RM_View_Form_Field_Editor('Ответ', 'response', ''))
    ->add(new RM_View_Form_Field_Select('Кто ответил', 'id_doctor', array_merge(
        array(0 => 'Отсутствует') ,$this->toSelect(
        Application_Model_Medical_Doctor::getList()
    ))));

echo $form->render();