<?php
use Application_Model_User_Profile as User;
use Application_Model_Medical_Doctor as Doctor;
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$time = $this->TimeSplitter()->splitTimeIntoHoursMinutes(15);
if ( $this->doctor instanceof Doctor && !Application_Model_Api_Google_AccessToken::getByDoctor($this->doctor) ) : ?>
    <a href="<?=MedOptima_Service_Google_Config::getCalendarClient($this->doctor->getId())->createAuthUrl()?>"
       class="main-links download-button">Link Google Account</a><?
endif;

$form
    ->add( new RM_View_Form_Field_Select('Пользователь', 'id_user', array_merge(array(
        0 => 'Отсутствует'
    ), $this->toSelect(User::getList(), function (User $user) {
        return $user->getFullName();
    }) )))
    ->add(new RM_View_Form_Field_Image('Фото', 'id_photo', 0, 255, 175))
    ->add(new RM_View_Form_Field_Text('Имя', 'firstName', []))
    ->add(new RM_View_Form_Field_Text('Фамилия', 'secondName', []))
    ->add(new RM_View_Form_Field_Textarea('Описание', 'description', []))
    ->add(new RM_View_Form_Field_Multiselect(
        'Должность',
        'id_posts',
        $this->toSelect(Application_Model_Medical_Post::getList()), array()
    ))
    ->add(new RM_View_Form_Field_ToMany('Услуги', 'id_services', array(), array(
        'class' => 'Application_Model_Medical_Service',
        'type' => 'option',
        'url' => $this->url([], 'admin-medical-service-ajax')
    )))
    ->add(new MedOptima_Admin_View_Form_Field_MultiListSelect('График работы', 'schedule', 3, array(
        MedOptima_Date_Time::getWeekDayNames(),
        $time, $time
    )));

echo $form->render();