<?php
$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$time = $this->TimeSplitter()->splitTimeIntoHoursMinutes(15);

$form
    ->add(new RM_View_Form_Field_Image('Фото', 'id_photo', 0, 255, 175))
    ->add(new RM_View_Form_Field_Text('Имя', 'firstName', []))
    ->add(new RM_View_Form_Field_Text('Фамилия', 'secondName', []))
    ->add(new RM_View_Form_Field_Textarea('Описание', 'description', []))
    ->add(new RM_View_Form_Field_Multiselect(
        'Должность',
        'id_posts',
        $this->toSelect(Application_Model_Medical_Post::getList()), array()
    ))
    ->add(new RM_View_Form_Field_ToMany('Услуги', 'id_services', array(), array(
        'class' => 'Application_Model_Medical_Service',
        'type' => 'option',
        'url' => $this->url([], 'admin-medical-service-ajax')
    )))
    ->add(new RM_View_Form_Field_MultiListSelect('График работы', 'schedule', 3, array(
        MedOptima_Date_Time::getWeekDayNames(),
        $time, $time
    )));

echo $form->render();