<?php
use Application_Model_User_Profile as User;

$form = new RM_View_Form();
$form->getLangPanel()->allLangs();

$time = $this->TimeSplitter()->splitTimeIntoHoursMinutes(15);

$form
    ->add( new RM_View_Form_Field_Select('Пользователь', 'id_user', array_merge(array(
        0 => 'Отсутствует'
    ), $this->toSelect(User::getList(), function (User $user) {
        return $user->getFullName();
    }) )))
    ->add(new RM_View_Form_Field_Image('Фото', 'id_photo', 0, 255, 175))
    ->add(new RM_View_Form_Field_Text('Имя', 'firstName', []))
    ->add(new RM_View_Form_Field_Text('Фамилия', 'secondName', []))
    ->add(new RM_View_Form_Field_Textarea('Описание', 'description', []))
    ->add(new RM_View_Form_Field_Multiselect(
        'Должность',
        'id_posts',
        $this->toSelect(Application_Model_Medical_Post::getList()),
        []
    ))
    ->add(new RM_View_Form_Field_Multiselect(
        'Услуги',
        'id_services',
        $this->toSelect(Application_Model_Medical_Service::getList()),
        []
    ))
    ->add(new MedOptima_Admin_View_Form_Field_MultiListSelect('График работы', 'work_time_list', 3, array(
        MedOptima_DateTime::getWeekdayNames(),
        $time, $time
    )))
    ->add(new RM_View_Form_Field_Select('Средняя продолжительность приема', 'reception_duration',
        $this->DateTime_InsideDayDuration()->splitRange('00:15', '03:00', '00:15'), 900
    ));

    if ($this->doctor instanceof Application_Model_Medical_Doctor) { // if edit action
        $form->add(new MedOptima_Admin_View_Form_Field_GoogleLink($this->doctor));
    }

echo $form->render();